### ISSUE TITLE
Request: avoid destroying shell scrollback

### ISSUE THREAD

**Issue by supermario** [lydell/elm-watch#45]
It appears `elm-watch` tries to destroy scrollback history:

<img width="851" alt="Screenshot 2022-11-02 at 11 09 39" src="https://user-images.githubusercontent.com/102781/199475134-827748bf-628c-46ac-8e3f-a9a774b9dfd9.png">

Other CLI tools that have a similar keep-replacing-previous-output displays (like `vite`) don't do this.

I found this quite surprising discovering that all my terminal history had disappeared (after initially hitting allow), and a little frustrating. I presume there's a good reason for it, but wanted to give the feedback in case it was avoidable. 🤗 

Not urgent as I've now set my setting to "always deny", and it now seems to work as vite does.

**Comment by lydell** [comment]
I haven’t used Vite much, so I might be missing something. But as far as I can tell, it works in a way that I don’t like.

Terminals have a “regular clear screen” command, which basically fills the screen with newlines. So the screen appears blank, but if you scroll up you can see what was there before. Vite uses this approach.

For Elm, it’s common that you get a _lot_ of errors at once, more than can fit the screen. So you need to scroll. I _really_ dislike when it’s possible for me to scroll up to errors from a _previous_ run, which now are out of date and a waste of time to look at. But you might look at them by mistake, not noticing you scrolled too far.

That’s why elm-watch also clears the scrollback.

I’ve noticed iTerm2 showing that message in your screenshot, too. I of course picked “Always Allow” since that’s what I want. I’ve noticed colleagues getting the message as well, but not understanding what it’s for.

Finally, there’s one more way to clear the screen. `htop` and `less`, for example, are “full screen”, but when you exit them, your terminal session “comes back.” That’s because they use the “alternate screen” which is a terminal concept. It lets you draw a full screen app while keeping the “real” terminal session behind.

That sounds perfect for elm-watch, so why don’t I use it? Because in the alternate screen you get no native scrolling – you have to implement scrolling yourself. Which I technically could (Vim does, for example), but that’s a line-based scroll instead of a pixel-based, smooth scroll that most terminal emulators use otherwise. And at least iTerm2 “remembers” my scroll position between elm-watch compilation cycles, which is nice too.

So, _not_ using the alternate screen and clearing the scrollback gives the best user experience in my opinion. Personally, I don’t mind “losing” my terminal history, because I always have two tabs open: One for elm-watch (and other watchers, via run-pty), and one for “real terminal work.” The watcher tab is always occupied with watchers, so I can’t really do anything in it, besides interacting with the watchers. This means I never have anything to lose there. And I keep the watchers running for the whole day – I don’t stop and restart and use that terminal tab for other things.

I have plans for a redesigned terminal experience, though, with showing one error at a time and interactivity and stuff: https://github.com/lydell/elm-watch/issues/43. So as part of that work, it _might_ make sense to start using the alternate screen (depends on how scrolling ends up feeling). However, since I (and a few others, it seems) use elm-watch in run-pty, it still might make sense to _not_ use the alternate screen for reasons I don’t have time to explain right now but that I need to keep in mind. (After all, I write this software for myself mainly, but if others like it too, that’s a nice bonus.)

Small note I felt like including for some reason: `elm-test --watch` (node-test-runner) also clears the scrollback, and after a quick search I couldn’t find any discussion about it in the issue tracker.

So my feeling here is that, in my opinion there’s good reason for elm-watch to do what it does, and you might be an outlier here. Luckily, you use a terminal that lets you switch to your desired behavior.
