### ISSUE TITLE
using a known hostname but dynamic port

### ISSUE THREAD

**Issue by BrianHicks** [lydell/elm-watch#88]
At work, we have to develop the frontend through a proxy. That makes `webSocketUrl` an absolute necessity, so we're using the beta version of `elm-watch`. However, sometimes the process manager tries to start a new `elm-watch` instance before the old one has exited, so we get port conflicts and the app fails to start. This isn't the _hugest_ problem—we can just restart the watcher—but it makes me wonder if it'd make sense to specify the components of the URL separately. For example, instead of:

```json
{
  "webSocketUrl": "ws://localhost:3002/elm-watch"
}
```

I wonder if we could do:

```json
{
  "webSocketUrl": {
    "secure": false,
    "host": "localhost"
  }
}
```

Or even use the pseudo-syntax that you show in the examples!

```json
{
  "webSocketUrl": "ws://localhost:${port}/elm-watch"
}
```

Longer-term, I hope to get rid of the process manager that's exhibiting this iffy behavior, but this would help sand down a rough edge in the mean time!

**Comment by BrianHicks** [comment]
hmm, actually, I did a little more searching and I think in the long term we may just want to use the server! But the short-term point still stands.

**Comment by lydell** [comment]
Hi! The idea was to use the `ELM_WATCH_WEBSOCKET_URL` environment variable when you need something dynamic. Have you tried that?

**Comment by lydell** [comment]
https://github.com/lydell/elm-watch/issues/87#issuecomment-1967254443 would allow this to be dynamic as well.

**Comment by lydell** [comment]
Then I must have failed again understanding exactly what you meant 😅

**Comment by lydell** [comment]
Hmm, so is this correct?

1. Your dev site is on `app.mycorp-dev.com`
2. By default elm-watch connects to the same hostname, but you want it to connect to `localhost`
3. You can configure the hostname via `webSocketUrl`, but then you also have to set the port
4. By default elm-watch gets a free port from the OS, but you have to set the port to a known value so that you can use `webSocketUrl`, but that sometimes results in a port conflict
5. So you want to be able to use the hostname but not the port, because you think that would avoid the port conflict?

If so, I’m not sure that would help. When elm-watch gets a free port from the OS, it saves that port in `elm-stuff/elm-watch/stuff.json`, so it can connect to the same port next time. So I’m thinking you’d get port conflicts anyway?
